#%RAML 0.8
title: Swagger Petstore
version: 1.0.0
documentation:
- title: Swagger Petstore
  content: A sample API that uses a petstore as an example to demonstrate features in the swagger-2.0 specification
baseUri: http://petstore.swagger.io/api
schemas:
- Pet-array: |
    {
      "type": "array",
      "items": {
        "id": "Pet",
        "title": "Pet",
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "tag": {
            "type": "string"
          },
          "id": {
            "type": "integer",
            "format": "int32"
          }
        },
        "required": [
          "name",
          "id"
        ]
      }
    }
- NewPet: |
    {
      "id": "NewPet",
      "title": "NewPet",
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "tag": {
          "type": "string"
        }
      },
      "required": [
        "name"
      ]
    }
- Pet: |
    {
      "id": "Pet",
      "title": "Pet",
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "tag": {
          "type": "string"
        },
        "id": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": [
        "name",
        "id"
      ]
    }
/pets:
  /{id}:
    uriParameters:
      id:
        description: ID of pet to fetch
        type: integer
        default: 
        required: true
        displayName: id
    get:
      displayName: findPetById
      description: Returns a user based on a single ID, if the user does not have access to the pet
      responses:
        200:
          description: pet response
          body:
            application/json:
              schema: Pet
        500:
          description: unexpected error
    delete:
      displayName: deletePet
      description: deletes a single pet based on the ID supplied
      responses:
        500:
          description: unexpected error
  get:
    displayName: findPets
    description: Returns all pets from the system that the user has access to
    responses:
      200:
        description: pet response
        body:
          application/json:
            schema: Pet-array
      500:
        description: unexpected error
    queryParameters:
      tags:
        description: tags to filter by
        type: string
        default: 
        required: false
        displayName: tags
      limit:
        description: maximum number of results to return
        type: integer
        default: 
        required: false
        displayName: limit
  post:
    body:
      application/json:
        schema: NewPet
    displayName: addPet
    description: Creates a new pet in the store.  Duplicates are allowed
    responses:
      200:
        description: pet response
        body:
          application/json:
            schema: Pet
      500:
        description: unexpected error
